services:
    _defaults:
        autowire: true
        autoconfigure: true

    exporttoolkit.event_listener:
        class: Elements\Bundle\ExportToolkitBundle\EventListener\ExportListener
#        lazy: true
        arguments:
            - "@exporttoolkit.exportservice"
        tags:
            - { name: kernel.event_subscriber }

    exporttoolkit.exportservice:
        class: Elements\Bundle\ExportToolkitBundle\ExportService

    Elements\Bundle\ExportToolkitBundle\Command\:
        resource: '../../Command'
        arguments:
            $name: 'export_name' 

    Elements\Bundle\ExportToolkitBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
